server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usermanagement?createDatabaseIfNotExist=true
    username: root
    password: test
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttle:
            enable: true
logging:
  level:
    org:
      hibernate:
        type: info